// Mocks generated by Mockito 5.4.6 from annotations
// in splitwithfriends/integration_test/app_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:splitwithfriends/models.dart' as _i2;
import 'package:splitwithfriends/services.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeExpense_0 extends _i1.SmartFake implements _i2.Expense {
  _FakeExpense_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SplitWithMeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSplitWithMeService extends _i1.Mock
    implements _i3.SplitWithMeService {
  MockSplitWithMeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Friend>> fetchFriends() =>
      (super.noSuchMethod(
            Invocation.method(#fetchFriends, []),
            returnValue: _i4.Future<List<_i2.Friend>>.value(<_i2.Friend>[]),
          )
          as _i4.Future<List<_i2.Friend>>);

  @override
  _i4.Future<List<_i2.Expense>> listExpenses() =>
      (super.noSuchMethod(
            Invocation.method(#listExpenses, []),
            returnValue: _i4.Future<List<_i2.Expense>>.value(<_i2.Expense>[]),
          )
          as _i4.Future<List<_i2.Expense>>);

  @override
  _i4.Future<_i2.Expense> getExpense(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getExpense, [id]),
            returnValue: _i4.Future<_i2.Expense>.value(
              _FakeExpense_0(this, Invocation.method(#getExpense, [id])),
            ),
          )
          as _i4.Future<_i2.Expense>);

  @override
  _i4.Future<_i2.Expense> createExpense(_i2.Expense? expense) =>
      (super.noSuchMethod(
            Invocation.method(#createExpense, [expense]),
            returnValue: _i4.Future<_i2.Expense>.value(
              _FakeExpense_0(
                this,
                Invocation.method(#createExpense, [expense]),
              ),
            ),
          )
          as _i4.Future<_i2.Expense>);

  @override
  _i4.Future<void> updateExpense(int? id, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateExpense, [id, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteExpense(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExpense, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Expense>> listFriendExpenses(int? friendId) =>
      (super.noSuchMethod(
            Invocation.method(#listFriendExpenses, [friendId]),
            returnValue: _i4.Future<List<_i2.Expense>>.value(<_i2.Expense>[]),
          )
          as _i4.Future<List<_i2.Expense>>);

  @override
  _i4.Future<List<_i2.Friend>> listExpenseFriends(int? expenseId) =>
      (super.noSuchMethod(
            Invocation.method(#listExpenseFriends, [expenseId]),
            returnValue: _i4.Future<List<_i2.Friend>>.value(<_i2.Friend>[]),
          )
          as _i4.Future<List<_i2.Friend>>);

  @override
  _i4.Future<void> updateFriendCredit(
    int? expenseId,
    int? friendId,
    double? amount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateFriendCredit, [
              expenseId,
              friendId,
              amount,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
